// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GameWoVacReq.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicompay.ice;

public abstract class Callback_GameWoVacReq_getVacReq extends Ice.TwowayCallback
{
	public abstract void response(ResVacBean __ret);

	public final void __completed(Ice.AsyncResult __result)
	{
		GameWoVacReqPrx __proxy = (GameWoVacReqPrx) __result.getProxy();
		ResVacBean __ret = null;
		try
		{
			__ret = __proxy.end_getVacReq(__result);
		}
		catch (Ice.LocalException __ex)
		{
			exception(__ex);
			return;
		}
		response(__ret);
	}
}
