// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GameWoVacReq.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicompay.ice;

public final class GameWoVacReqPrxHelper extends Ice.ObjectPrxHelperBase implements GameWoVacReqPrx
{
	private static final String __getVacReq_name = "getVacReq";

	public ResVacBean getVacReq(ReqVacBean vbean)
	{
		return getVacReq(vbean, null, false);
	}

	public ResVacBean getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx)
	{
		return getVacReq(vbean, __ctx, true);
	}

	private ResVacBean getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, boolean __explicitCtx)
	{
		if (__explicitCtx && __ctx == null)
		{
			__ctx = _emptyContext;
		}
		final Ice.Instrumentation.InvocationObserver __observer = IceInternal.ObserverHelper.get(this, "getVacReq", __ctx);
		int __cnt = 0;
		try
		{
			while (true)
			{
				Ice._ObjectDel __delBase = null;
				try
				{
					__checkTwowayOnly("getVacReq");
					__delBase = __getDelegate(false);
					_GameWoVacReqDel __del = (_GameWoVacReqDel) __delBase;
					return __del.getVacReq(vbean, __ctx, __observer);
				}
				catch (IceInternal.LocalExceptionWrapper __ex)
				{
					__handleExceptionWrapper(__delBase, __ex, __observer);
				}
				catch (Ice.LocalException __ex)
				{
					__cnt = __handleException(__delBase, __ex, null, __cnt, __observer);
				}
			}
		}
		finally
		{
			if (__observer != null)
			{
				__observer.detach();
			}
		}
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean)
	{
		return begin_getVacReq(vbean, null, false, null);
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx)
	{
		return begin_getVacReq(vbean, __ctx, true, null);
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, Ice.Callback __cb)
	{
		return begin_getVacReq(vbean, null, false, __cb);
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, Ice.Callback __cb)
	{
		return begin_getVacReq(vbean, __ctx, true, __cb);
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, Callback_GameWoVacReq_getVacReq __cb)
	{
		return begin_getVacReq(vbean, null, false, __cb);
	}

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, Callback_GameWoVacReq_getVacReq __cb)
	{
		return begin_getVacReq(vbean, __ctx, true, __cb);
	}

	private Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, boolean __explicitCtx,
			IceInternal.CallbackBase __cb)
	{
		__checkAsyncTwowayOnly(__getVacReq_name);
		IceInternal.OutgoingAsync __result = new IceInternal.OutgoingAsync(this, __getVacReq_name, __cb);
		try
		{
			__result.__prepare(__getVacReq_name, Ice.OperationMode.Normal, __ctx, __explicitCtx);
			IceInternal.BasicStream __os = __result.__startWriteParams(Ice.FormatType.DefaultFormat);
			vbean.__write(__os);
			__result.__endWriteParams();
			__result.__send(true);
		}
		catch (Ice.LocalException __ex)
		{
			__result.__exceptionAsync(__ex);
		}
		return __result;
	}

	public ResVacBean end_getVacReq(Ice.AsyncResult __result)
	{
		Ice.AsyncResult.__check(__result, this, __getVacReq_name);
		boolean __ok = __result.__wait();
		try
		{
			if (!__ok)
			{
				try
				{
					__result.__throwUserException();
				}
				catch (Ice.UserException __ex)
				{
					throw new Ice.UnknownUserException(__ex.ice_name(), __ex);
				}
			}
			IceInternal.BasicStream __is = __result.__startReadParams();
			ResVacBean __ret;
			__ret = new ResVacBean();
			__ret.__read(__is);
			__result.__endReadParams();
			return __ret;
		}
		catch (Ice.LocalException ex)
		{
			Ice.Instrumentation.InvocationObserver __obsv = __result.__getObserver();
			if (__obsv != null)
			{
				__obsv.failed(ex.ice_name());
			}
			throw ex;
		}
	}

	public static GameWoVacReqPrx checkedCast(Ice.ObjectPrx __obj)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			if (__obj instanceof GameWoVacReqPrx)
			{
				__d = (GameWoVacReqPrx) __obj;
			}
			else
			{
				if (__obj.ice_isA(ice_staticId()))
				{
					GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
					__h.__copyFrom(__obj);
					__d = __h;
				}
			}
		}
		return __d;
	}

	public static GameWoVacReqPrx checkedCast(Ice.ObjectPrx __obj, java.util.Map<String, String> __ctx)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			if (__obj instanceof GameWoVacReqPrx)
			{
				__d = (GameWoVacReqPrx) __obj;
			}
			else
			{
				if (__obj.ice_isA(ice_staticId(), __ctx))
				{
					GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
					__h.__copyFrom(__obj);
					__d = __h;
				}
			}
		}
		return __d;
	}

	public static GameWoVacReqPrx checkedCast(Ice.ObjectPrx __obj, String __facet)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
			try
			{
				if (__bb.ice_isA(ice_staticId()))
				{
					GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
					__h.__copyFrom(__bb);
					__d = __h;
				}
			}
			catch (Ice.FacetNotExistException ex)
			{
			}
		}
		return __d;
	}

	public static GameWoVacReqPrx checkedCast(Ice.ObjectPrx __obj, String __facet, java.util.Map<String, String> __ctx)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
			try
			{
				if (__bb.ice_isA(ice_staticId(), __ctx))
				{
					GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
					__h.__copyFrom(__bb);
					__d = __h;
				}
			}
			catch (Ice.FacetNotExistException ex)
			{
			}
		}
		return __d;
	}

	public static GameWoVacReqPrx uncheckedCast(Ice.ObjectPrx __obj)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			if (__obj instanceof GameWoVacReqPrx)
			{
				__d = (GameWoVacReqPrx) __obj;
			}
			else
			{
				GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
				__h.__copyFrom(__obj);
				__d = __h;
			}
		}
		return __d;
	}

	public static GameWoVacReqPrx uncheckedCast(Ice.ObjectPrx __obj, String __facet)
	{
		GameWoVacReqPrx __d = null;
		if (__obj != null)
		{
			Ice.ObjectPrx __bb = __obj.ice_facet(__facet);
			GameWoVacReqPrxHelper __h = new GameWoVacReqPrxHelper();
			__h.__copyFrom(__bb);
			__d = __h;
		}
		return __d;
	}

	public static final String[] __ids = { "::Ice::Object", "::intervac::GameWoVacReq" };

	public static String ice_staticId()
	{
		return __ids[1];
	}

	protected Ice._ObjectDelM __createDelegateM()
	{
		return new _GameWoVacReqDelM();
	}

	protected Ice._ObjectDelD __createDelegateD()
	{
		return new _GameWoVacReqDelD();
	}

	public static void __write(IceInternal.BasicStream __os, GameWoVacReqPrx v)
	{
		__os.writeProxy(v);
	}

	public static GameWoVacReqPrx __read(IceInternal.BasicStream __is)
	{
		Ice.ObjectPrx proxy = __is.readProxy();
		if (proxy != null)
		{
			GameWoVacReqPrxHelper result = new GameWoVacReqPrxHelper();
			result.__copyFrom(proxy);
			return result;
		}
		return null;
	}

	public static final long serialVersionUID = 0L;
}
