// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SmInt.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicomsms.ice;

public final class SmMsgHolder extends Ice.ObjectHolderBase<SmMsg>
{
	public SmMsgHolder()
	{
	}

	public SmMsgHolder(SmMsg value)
	{
		this.value = value;
	}

	public void patch(Ice.Object v)
	{
		if (v == null || v instanceof SmMsg)
		{
			value = (SmMsg) v;
		}
		else
		{
			IceInternal.Ex.throwUOE(type(), v);
		}
	}

	public String type()
	{
		return _SmMsgDisp.ice_staticId();
	}
}
