// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SmInt.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicomsms.ice;

public interface SmMsgPrx extends Ice.ObjectPrx
{
	public int Login(String strUserName, String strPasswd);

	public int Login(String strUserName, String strPasswd, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd, Ice.Callback __cb);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd, Callback_SmMsg_Login __cb);

	public Ice.AsyncResult begin_Login(String strUserName, String strPasswd, java.util.Map<String, String> __ctx, Callback_SmMsg_Login __cb);

	public int end_Login(Ice.AsyncResult __result);

	public int OnMt(Mt sMt, Ice.StringHolder strGWID);

	public int OnMt(Mt sMt, Ice.StringHolder strGWID, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMt(Mt sMt);

	public Ice.AsyncResult begin_OnMt(Mt sMt, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMt(Mt sMt, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMt(Mt sMt, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMt(Mt sMt, Callback_SmMsg_OnMt __cb);

	public Ice.AsyncResult begin_OnMt(Mt sMt, java.util.Map<String, String> __ctx, Callback_SmMsg_OnMt __cb);

	public int end_OnMt(Ice.StringHolder strGWID, Ice.AsyncResult __result);

	public int OnMtResp(MtResp sResp);

	public int OnMtResp(MtResp sResp, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp, Callback_SmMsg_OnMtResp __cb);

	public Ice.AsyncResult begin_OnMtResp(MtResp sResp, java.util.Map<String, String> __ctx, Callback_SmMsg_OnMtResp __cb);

	public int end_OnMtResp(Ice.AsyncResult __result);

	public int OnReport(MtReport sReport);

	public int OnReport(MtReport sReport, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnReport(MtReport sReport);

	public Ice.AsyncResult begin_OnReport(MtReport sReport, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnReport(MtReport sReport, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnReport(MtReport sReport, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnReport(MtReport sReport, Callback_SmMsg_OnReport __cb);

	public Ice.AsyncResult begin_OnReport(MtReport sReport, java.util.Map<String, String> __ctx, Callback_SmMsg_OnReport __cb);

	public int end_OnReport(Ice.AsyncResult __result);

	public int OnMo(Mo sMo);

	public int OnMo(Mo sMo, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMo(Mo sMo);

	public Ice.AsyncResult begin_OnMo(Mo sMo, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_OnMo(Mo sMo, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMo(Mo sMo, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_OnMo(Mo sMo, Callback_SmMsg_OnMo __cb);

	public Ice.AsyncResult begin_OnMo(Mo sMo, java.util.Map<String, String> __ctx, Callback_SmMsg_OnMo __cb);

	public int end_OnMo(Ice.AsyncResult __result);
}
