// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SmInt.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicomsms.ice;

public interface _SmMsgDel extends Ice._ObjectDel
{
	int Login(String strUserName, String strPasswd, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
			throws IceInternal.LocalExceptionWrapper;

	int OnMt(Mt sMt, Ice.StringHolder strGWID, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
			throws IceInternal.LocalExceptionWrapper;

	int OnMtResp(MtResp sResp, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
			throws IceInternal.LocalExceptionWrapper;

	int OnReport(MtReport sReport, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
			throws IceInternal.LocalExceptionWrapper;

	int OnMo(Mo sMo, java.util.Map<String, String> __ctx, Ice.Instrumentation.InvocationObserver __obsv)
			throws IceInternal.LocalExceptionWrapper;
}
