// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SmInt.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicomsms.ice;

public interface _SmMsgOperations
{
	int Login(String strUserName, String strPasswd, Ice.Current __current);

	int OnMt(Mt sMt, Ice.StringHolder strGWID, Ice.Current __current);

	int OnMtResp(MtResp sResp, Ice.Current __current);

	int OnReport(MtReport sReport, Ice.Current __current);

	int OnMo(Mo sMo, Ice.Current __current);
}
