// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `SmInt.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicomsms.ice;

public class MtReport implements java.lang.Cloneable, java.io.Serializable
{
	public String strGWID;

	public byte cReportType;

	public String strUserNumber;

	public byte cStatus;

	public byte cErrorCode;

	public String strReserve;

	public MtReport()
	{
	}

	public MtReport(String strGWID, byte cReportType, String strUserNumber, byte cStatus, byte cErrorCode, String strReserve)
	{
		this.strGWID = strGWID;
		this.cReportType = cReportType;
		this.strUserNumber = strUserNumber;
		this.cStatus = cStatus;
		this.cErrorCode = cErrorCode;
		this.strReserve = strReserve;
	}

	public boolean equals(java.lang.Object rhs)
	{
		if (this == rhs)
		{
			return true;
		}
		MtReport _r = null;
		if (rhs instanceof MtReport)
		{
			_r = (MtReport) rhs;
		}

		if (_r != null)
		{
			if (strGWID != _r.strGWID)
			{
				if (strGWID == null || _r.strGWID == null || !strGWID.equals(_r.strGWID))
				{
					return false;
				}
			}
			if (cReportType != _r.cReportType)
			{
				return false;
			}
			if (strUserNumber != _r.strUserNumber)
			{
				if (strUserNumber == null || _r.strUserNumber == null || !strUserNumber.equals(_r.strUserNumber))
				{
					return false;
				}
			}
			if (cStatus != _r.cStatus)
			{
				return false;
			}
			if (cErrorCode != _r.cErrorCode)
			{
				return false;
			}
			if (strReserve != _r.strReserve)
			{
				if (strReserve == null || _r.strReserve == null || !strReserve.equals(_r.strReserve))
				{
					return false;
				}
			}

			return true;
		}

		return false;
	}

	public int hashCode()
	{
		int __h = 5381;
		__h = IceInternal.HashUtil.hashAdd(__h, "::SmModule::MtReport");
		__h = IceInternal.HashUtil.hashAdd(__h, strGWID);
		__h = IceInternal.HashUtil.hashAdd(__h, cReportType);
		__h = IceInternal.HashUtil.hashAdd(__h, strUserNumber);
		__h = IceInternal.HashUtil.hashAdd(__h, cStatus);
		__h = IceInternal.HashUtil.hashAdd(__h, cErrorCode);
		__h = IceInternal.HashUtil.hashAdd(__h, strReserve);
		return __h;
	}

	public java.lang.Object clone()
	{
		java.lang.Object o = null;
		try
		{
			o = super.clone();
		}
		catch (CloneNotSupportedException ex)
		{
			assert false; // impossible
		}
		return o;
	}

	public void __write(IceInternal.BasicStream __os)
	{
		__os.writeString(strGWID);
		__os.writeByte(cReportType);
		__os.writeString(strUserNumber);
		__os.writeByte(cStatus);
		__os.writeByte(cErrorCode);
		__os.writeString(strReserve);
	}

	public void __read(IceInternal.BasicStream __is)
	{
		strGWID = __is.readString();
		cReportType = __is.readByte();
		strUserNumber = __is.readString();
		cStatus = __is.readByte();
		cErrorCode = __is.readByte();
		strReserve = __is.readString();
	}

	public static final long serialVersionUID = 685704150L;
}
