// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GameWoVacReq.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicompay.ice;

public final class GameWoVacReqHolder extends Ice.ObjectHolderBase<GameWoVacReq>
{
	public GameWoVacReqHolder()
	{
	}

	public GameWoVacReqHolder(GameWoVacReq value)
	{
		this.value = value;
	}

	public void patch(Ice.Object v)
	{
		if (v == null || v instanceof GameWoVacReq)
		{
			value = (GameWoVacReq) v;
		}
		else
		{
			IceInternal.Ex.throwUOE(type(), v);
		}
	}

	public String type()
	{
		return _GameWoVacReqDisp.ice_staticId();
	}
}
