// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GameWoVacReq.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.newspace.payplatform.unicompay.ice;

public interface GameWoVacReqPrx extends Ice.ObjectPrx
{
	public ResVacBean getVacReq(ReqVacBean vbean);

	public ResVacBean getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, Ice.Callback __cb);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, Ice.Callback __cb);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, Callback_GameWoVacReq_getVacReq __cb);

	public Ice.AsyncResult begin_getVacReq(ReqVacBean vbean, java.util.Map<String, String> __ctx, Callback_GameWoVacReq_getVacReq __cb);

	public ResVacBean end_getVacReq(Ice.AsyncResult __result);
}
